environments:
  - name: dev
    configs:  
      endpoints:
        production:
          url: https://localhost:9443/am/sample/pizzashack/v1/api/
        sandbox: 
          url: https://localhost:9443/am/sample/pizzashack/v1/api/   
      deploymentEnvironments:
        - displayOnDevportal: true
          deploymentEnvironment: UniversalGW
          deploymentVhost: apim.dev.apis.coach
      policies:
        - Gold

  - name: uat
    configs:
      endpoints:
        production:
          url: https://localhost:9443/am/sample/pizzashack/v1/api/
      deploymentEnvironments:
        - displayOnDevportal: true
          deploymentEnvironment: UniversalGW
          deploymentVhost: apim.uat.apis.coach
      policies:
        - Unlimited
        - Gold