on:
  push:
    paths:
      - apim/**/Conf/*.zip
    branches:
      - main
  workflow_dispatch:

name: Build and Release API Repo

jobs:
  release_repo:
    name: Release Repo
    uses: isamauny-wso2/wso2-workflows/.github/workflows/release-apim-api.yml@main
    secrets: inherit